"""empty message

Revision ID: 45af7fc9f5ba
Revises: 
Create Date: 2020-08-10 00:08:47.983736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45af7fc9f5ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('senha', sa.String(length=512), nullable=False),
    sa.Column('data_cr', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('data_cr', sa.DateTime(), nullable=False),
    sa.Column('body_post', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imgPost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('data_upl', sa.DateTime(), nullable=False),
    sa.Column('imagem_dt', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['id_post'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imgPost')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
