"""empty message

Revision ID: e705c6c82d81
Revises: 0f320e7f37bc
Create Date: 2020-08-08 23:11:27.276629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e705c6c82d81'
down_revision = '0f320e7f37bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('senha', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'senha')
    # ### end Alembic commands ###
